FROM python:2.7.13-slim

RUN pip install celery flask flower gevent pyyaml cwlref-runner && \
    apt-get -y update && \
    apt-get -y install curl wget vim && \
    wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && \
    chmod 0755 jq-linux64 && mv jq-linux64 /usr/local/bin/. 

ADD . /root/server/
WORKDIR /root/server
RUN cp bin/* /usr/local/bin/.

CMD ["/root/server/run.sh"]
